version: '3.8'

services:
  backend:
    build:
      context: ./server
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=12345
      - DATABASE_NAME=mycars
    depends_on:
      - postgres  
    networks:
      - app-network

  frontend:
    build:
      context: ./client
    container_name: frontend
    ports:
      - "4201:4201"
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: mycars
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:  
    driver: local  # Default local driver for storing volume data on the host

networks:
  app-network:  
    driver: bridge  # Bridge network driver allows containers to communicate with each other